/**
 * List of all available WordPress Dashicons
 */
export const dashicons = [
    'admin-appearance', 'admin-collapse', 'admin-comments', 'admin-customizer', 'admin-generic',
    'admin-home', 'admin-links', 'admin-media', 'admin-multisite', 'admin-network',
    'admin-page', 'admin-plugins', 'admin-post', 'admin-settings', 'admin-site',
    'admin-tools', 'admin-users', 'album', 'align-center', 'align-left',
    'align-none', 'align-right', 'analytics', 'archive', 'arrow-down',
    'arrow-down-alt', 'arrow-down-alt2', 'arrow-left', 'arrow-left-alt', 'arrow-left-alt2',
    'arrow-right', 'arrow-right-alt', 'arrow-right-alt2', 'arrow-up', 'arrow-up-alt',
    'arrow-up-alt2', 'art', 'awards', 'backup', 'book',
    'book-alt', 'building', 'businessman', 'calendar', 'calendar-alt',
    'camera', 'carrot', 'cart', 'category', 'chart-area',
    'chart-bar', 'chart-line', 'chart-pie', 'clipboard', 'clock',
    'cloud', 'cloud-saved', 'cloud-upload', 'code-standards', 'coffee',
    'color-picker', 'columns', 'controls-back', 'controls-forward', 'controls-pause',
    'controls-play', 'controls-repeat', 'controls-skipback', 'controls-skipforward', 'controls-volumeoff',
    'controls-volumeon', 'dashboard', 'database', 'desktop', 'dismiss',
    'download', 'editor-aligncenter', 'editor-alignleft', 'editor-alignright', 'editor-bold',
    'editor-break', 'editor-code', 'editor-contract', 'editor-customchar', 'editor-expand',
    'editor-help', 'editor-indent', 'editor-insertmore', 'editor-italic', 'editor-justify',
    'editor-kitchensink', 'editor-ol', 'editor-outdent', 'editor-paragraph', 'editor-paste-text',
    'editor-paste-word', 'editor-quote', 'editor-removeformatting', 'editor-rtl', 'editor-spellcheck',
    'editor-strikethrough', 'editor-table', 'editor-textcolor', 'editor-ul', 'editor-underline',
    'editor-unlink', 'editor-video', 'email', 'email-alt', 'exerpt-view',
    'external', 'facebook', 'facebook-alt', 'feedback', 'filter',
    'flag', 'format-aside', 'format-audio', 'format-chat', 'format-gallery',
    'format-image', 'format-links', 'format-quote', 'format-standard', 'format-status',
    'format-video', 'forms', 'googleplus', 'grid-view', 'groups',
    'hammer', 'heart', 'hidden', 'id', 'id-alt',
    'image-crop', 'image-filter', 'image-rotate', 'image-rotate-left', 'image-rotate-right',
    'images-alt', 'images-alt2', 'index-card', 'info', 'info-outline',
    'insert-after', 'insert-before', 'key', 'leftright', 'lightbulb',
    'list-view', 'location', 'location-alt', 'lock', 'marker',
    'media-archive', 'media-audio', 'media-code', 'media-default', 'media-document',
    'media-interactive', 'media-spreadsheet', 'media-text', 'media-video', 'megaphone',
    'menu', 'microphone', 'migrate', 'minus', 'money',
    'move', 'nametag', 'networking', 'no', 'no-alt',
    'palmtree', 'paperclip', 'performance', 'phone', 'playlist-audio',
    'playlist-video', 'plus', 'plus-alt', 'portfolio', 'post-status',
    'pressthis', 'products', 'randomize', 'redo', 'rss',
    'schedule', 'screenoptions', 'search', 'share', 'share-alt',
    'share-alt2', 'share1', 'shield', 'shield-alt', 'slides',
    'smartphone', 'smiley', 'sort', 'sos', 'star-empty',
    'star-filled', 'star-half', 'sticky', 'store', 'tablet',
    'tag', 'tagcloud', 'testimonial', 'text', 'thumbs-down',
    'thumbs-up', 'translation', 'trash', 'twitter', 'undo',
    'universal-access', 'universal-access-alt', 'unlock', 'update', 'upload',
    'vault', 'video-alt', 'video-alt2', 'video-alt3', 'visibility',
    'welcome-add-page', 'welcome-comments', 'welcome-edit-page', 'welcome-learn-more', 'welcome-view-site',
    'welcome-widgets-menus', 'welcome-write-blog', 'wordpress', 'wordpress-alt', 'yes',
    'yes-alt'
];